# Generated by Django 5.0.6 on 2024-06-14 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=250, null=True),
                ),
                ("body", models.TextField(blank=True, default="", null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "image1",
                    models.ImageField(blank=True, upload_to="uploads/sketches/"),
                ),
                ("caption1", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image2",
                    models.ImageField(blank=True, upload_to="uploads/sketches/"),
                ),
                ("caption2", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image3",
                    models.ImageField(blank=True, upload_to="uploads/sketches/"),
                ),
                ("caption3", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image4",
                    models.ImageField(blank=True, upload_to="uploads/sketches/"),
                ),
                ("caption4", models.CharField(blank=True, max_length=200, null=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
