# Generated by Django 5.0.6 on 2024-06-21 10:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_remove_article_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image1",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image1"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image2",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image2"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image3",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image3"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image4",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image4"
            ),
        ),
    ]
