# Generated by Django 5.0.6 on 2024-06-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=250, null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={"verbose_name_plural": "galleries",},
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/works/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="portfolio.gallery",
                    ),
                ),
            ],
        ),
    ]
